# Cloud Buildのステップを定義します
steps:
  # ステップ1: 依存関係のインストール
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    
  # ステップ2: Cloud Functionのデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'functions'
      - 'deploy'
      - 'ocrProcessor'
      - '--gen2'
      - '--runtime=nodejs20'
      - '--region=asia-northeast1'
      - '--source=.'
      - '--entry-point=ocrProcessor'
      - '--trigger-http'
      - '--allow-unauthenticated'

# ログ設定を追加
options:
  logging: CLOUD_LOGGING_ONLY
  
# タイムアウト時間を設定
timeout: '1200s'
